### ISSUE TITLE
make().with().oneAndPersist() and make().with().manyAndPersist() do not work

### ISSUE THREAD

**Issue by tolgap** [CyriacBr/mikro-resources#11]
Given these two extra test cases for `factory.test.ts`:

```javascript
describe(`Factory`, () => {
  let orm: MikroORM;
  let factory: FixtureFactory;

  beforeAll(async () => {
    orm = await MikroORM.init(ormConfig as any);
    await orm.getSchemaGenerator().dropSchema();
    await orm.getSchemaGenerator().createSchema();
    factory = new FixtureFactory(orm);
  });

  afterAll(() => orm.close());

  it(`make().with().oneAndPersist()`, async () => {
    const result = factory.make(Author).with({ age: 30 });
    expect(result.oneAndPersist).toBeInstanceOf(Function);
  });

  it(`make().with().manyAndPersist()`, async () => {
    const result = factory.make(Author).with({ age: 30 });
    expect(result.manyAndPersist).toBeInstanceOf(Function);
  });
})
```

Results in the following output:

```
  ● Factory › make().with().oneAndPersist()

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Function

    Received value has no prototype
    Received value: undefined

      58 |   it(`make().with().oneAndPersist()`, async () => {
      59 |     const result = factory.make(Author).with({ age: 30 });
    > 60 |     expect(result.oneAndPersist).toBeInstanceOf(Function);
         |                                  ^
      61 |   })
      62 |

      at test/factory.test.ts:60:34
      at step (node_modules/tslib/tslib.js:143:27)
      at Object.next (node_modules/tslib/tslib.js:124:57)
      at node_modules/tslib/tslib.js:117:75
      at Object.__awaiter (node_modules/tslib/tslib.js:113:16)
      at Object.<anonymous> (test/factory.test.ts:58:39)

  ● Factory › make().with().manyAndPersist()

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Function

    Received value has no prototype
    Received value: undefined

      79 |   it(`make().with().manyAndPersist()`, async () => {
      80 |     const result = factory.make(Author).with({ age: 30 });
    > 81 |     expect(result.manyAndPersist).toBeInstanceOf(Function);
         |                                   ^
      82 |   })
      83 |

      at test/factory.test.ts:81:35
      at step (node_modules/tslib/tslib.js:143:27)
      at Object.next (node_modules/tslib/tslib.js:124:57)
      at node_modules/tslib/tslib.js:117:75
      at Object.__awaiter (node_modules/tslib/tslib.js:113:16)
      at Object.<anonymous> (test/factory.test.ts:79:40)
```

This package is exactly what I'm looking for, but sadly this pattern does not work. I'm trying to use it for creating seeds.

**Comment by CyriacBr** [comment]
Good catch. This will be fixed in the next release once your PR is merged.
